// Preguntas del canal de Telegram (una al día, en orden; al acabar vuelve a empezar).
// Las publica api/telegram.js como encuesta en modo cuestionario.
// Límites de Telegram: pregunta ≤ 300 caracteres, cada opción ≤ 100, explicación ≤ 200.
// `ok` es la posición (empezando en 0) de la respuesta correcta; `link` es la página de la web
// que la explica más a fondo (se le añade ?utm_source=telegram al publicar).
module.exports = [
  { q: 'Te reparten A♠A♥ en UTG (primero en hablar) en una mesa de 6. ¿Qué haces?',
    opts: ['Limp, para disimular', 'Subir a 2,5 ciegas', 'All-in directamente'], ok: 1,
    why: 'Sube siempre: quieres un bote grande contra pocos rivales. Con limp entran más jugadores y los ases ganan menos veces.',
    link: '/manos/aa/' },
  { q: 'El rival apuesta medio bote. ¿Cuántas veces necesitas ganar para que pagar sea rentable?',
    opts: ['20%', '25%', '33%'], ok: 1,
    why: 'Bote 100, apuesta 50: pagas 50 para un bote final de 200. 50 ÷ 200 = 25%.',
    link: '/glosario/pot-odds/' },
  { q: 'En el flop tienes 4 cartas del mismo palo (2 en tu mano y 2 en la mesa). ¿Cuántos outs tienes para color?',
    opts: ['8', '9', '13'], ok: 1,
    why: 'Hay 13 cartas de cada palo y ya ves 4: quedan 9 en la baraja.',
    link: '/glosario/outs/' },
  { q: 'Tienes escalera abierta en el flop (8 outs). ¿Qué probabilidad aproximada tienes de ligarla hasta el river?',
    opts: ['16%', '32%', '50%'], ok: 1,
    why: 'Regla del 4 y del 2: en el flop, outs × 4. 8 × 4 = 32%.',
    link: '/guias/como-calcular-outs/' },
  { q: '¿Cada cuántas manos te reparten ases (AA), de media?',
    opts: ['1 de cada 50', '1 de cada 221', '1 de cada 1.000'], ok: 1,
    why: 'Hay 6 combinaciones de AA entre 1.326 manos posibles: 1 de cada 221 (0,45%).',
    link: '/guias/probabilidades-de-poker/' },
  { q: 'All-in antes del flop: QQ contra AK de distinto palo. ¿Quién es favorito?',
    opts: ['QQ', 'AK', 'Exactamente 50-50'], ok: 0,
    why: 'Es la famosa “moneda al aire”, pero la pareja va algo por delante: QQ gana alrededor del 56%.',
    link: '/manos/qq/' },
  { q: 'Tienes 7♣2♦ en el botón y todos se han retirado antes. ¿Qué haces?',
    opts: ['Subir para robar las ciegas', 'Retirarte', 'Limp'], ok: 1,
    why: '72o es la peor mano: sin palo ni conexión, casi nunca liga. Incluso desde el botón, lo normal es tirarla.',
    link: '/manos/72o/' },
  { q: 'Tienes 4♠4♥. Te suben a 3 ciegas y os quedan 100 a cada uno. ¿Pagas para buscar trío?',
    opts: ['Sí, compensa', 'No, las parejas pequeñas se tiran', 'Solo con 200 ciegas o más'], ok: 0,
    why: 'Regla del 15 a 1: 15 × 3 = 45 ciegas, y hay 100 detrás. Si ligas trío puedes cobrar lo suficiente.',
    link: '/guias/como-jugar-parejas-pequenas/' },
  { q: 'Con 3♦3♣ te hacen 3-bet a 12 ciegas y os quedan 100 a cada uno. ¿Pagas para buscar trío?',
    opts: ['Sí', 'No', 'All-in'], ok: 1,
    why: '15 × 12 = 180 ciegas y solo hay 100 detrás: aunque ligues trío no cobrarás lo suficiente. Retírate.',
    link: '/guias/como-jugar-parejas-pequenas/' },
  { q: '¿Cuál es la mejor posición de la mesa para jugar después del flop?',
    opts: ['UTG', 'Ciega grande', 'Botón'], ok: 2,
    why: 'En el botón hablas el último en todas las calles: ves qué hacen los demás antes de decidir.',
    link: '/glosario/posicion/' },
  { q: 'Empieza el flop con un bote de 20 y os quedan 100 a cada uno. ¿Cuál es el SPR?',
    opts: ['2', '5', '10'], ok: 1,
    why: 'SPR = stack efectivo ÷ bote = 100 ÷ 20 = 5. Con SPR medio, hay que pensar cada calle.',
    link: '/glosario/spr/' },
  { q: 'Subes con A♠Q♦ en el botón y paga la ciega grande. Flop: K♣7♦2♥. No has ligado. ¿Qué haces?',
    opts: ['Pasar', 'Apostar 1/3 del bote', 'All-in'], ok: 1,
    why: 'Flop alto y seco: tu rango tiene más reyes que el de la ciega grande. Una apuesta pequeña gana mucho.',
    link: '/guias/cuando-hacer-c-bet/' },
  { q: 'Apuestas el bote entero de farol. ¿Cuántas veces tiene que retirarse el rival para que ganes dinero?',
    opts: ['33%', '50%', '67%'], ok: 1,
    why: 'Arriesgas 1 bote para ganar 1 bote: necesitas que se retire al menos la mitad de las veces.',
    link: '/glosario/farol/' },
  { q: 'Torneo, tienes 20 ciegas y A♠K♦. Subes y te hacen all-in. ¿Qué haces?',
    opts: ['Pagar', 'Retirarte', 'Depende del flop'], ok: 0,
    why: 'Con 40 ciegas o menos, AK es casi siempre all-in: el rival empuja también con AQ, parejas medias y faroles.',
    link: '/guias/como-jugar-ak-preflop/' },
  { q: 'Estás en la ciega grande. El botón sube a 2,5 ciegas y la pequeña se retira. ¿Qué % necesitas ganar para pagar?',
    opts: ['27%', '40%', '50%'], ok: 0,
    why: 'Pagas 1,5 para un bote final de 5,5 ciegas: 1,5 ÷ 5,5 ≈ 27%. Por eso se defienden tantas manos.',
    link: '/guias/como-jugar-desde-la-ciega-grande/' },
  { q: '¿Cuál de estas manos es mejor para un 3-bet de farol?',
    opts: ['A5 del mismo palo', 'KJ de distinto palo', '72 de distinto palo'], ok: 0,
    why: 'El as quita combinaciones de AA y AK al rival, y si te pagan puedes ligar color o la escalera A-2-3-4-5.',
    link: '/manos/a5s/' },
  { q: 'Mesa K♥9♥4♠ y tienes 6♥5♥. ¿Cuál es el gran peligro de tu proyecto de color?',
    opts: ['Que no tienes outs', 'Que un color más alto te gane', 'Ninguno'], ok: 1,
    why: 'Si ligas color, un rival con A♥ o Q♥ tiene uno mejor. El proyecto de color al as vale mucho más.',
    link: '/guias/como-jugar-proyecto-de-color/' },
  { q: '¿Qué probabilidad hay de que te repartan una pareja cualquiera?',
    opts: ['1 de cada 6', '1 de cada 17', '1 de cada 50'], ok: 1,
    why: 'Hay 78 parejas posibles entre 1.326 manos: un 5,9%, más o menos 1 de cada 17.',
    link: '/guias/probabilidades-de-poker/' },
  { q: 'Tienes una pareja en la mano. ¿Qué probabilidad hay de ligar trío o mejor en el flop?',
    opts: ['5%', '12%', '25%'], ok: 1,
    why: 'Un 11,8%: aproximadamente 1 de cada 8,5 flops. Por eso las parejas pequeñas necesitan cobrar mucho cuando ligan.',
    link: '/manos/55/' },
  { q: 'Con AK, ¿cuántas veces ligas al menos una pareja en el flop?',
    opts: ['1 de cada 3', '1 de cada 2', '2 de cada 3'], ok: 0,
    why: 'Un 32%. El resto de veces tienes “as alto”: AK es muy buena mano, pero antes del flop no ha ligado nada.',
    link: '/manos/ako/' },
  { q: 'Tienes KK. ¿Con qué frecuencia sale al menos un as en el flop?',
    opts: ['5%', '23%', '50%'], ok: 1,
    why: 'Quedan 4 ases entre 50 cartas: sale al menos uno en el flop un 23% de las veces. Ahí toca frenar.',
    link: '/manos/kk/' },
  { q: 'Desde la ciega grande quieres hacer 3-bet contra una subida a 2,5 ciegas. ¿De cuánto?',
    opts: ['5 ciegas', '10 ciegas', '20 ciegas'], ok: 1,
    why: 'Fuera de posición se resube unas 4 veces la subida: 4 × 2,5 = 10. En posición, unas 3 veces.',
    link: '/glosario/3-bet/' },
  { q: 'Cash online, nadie ha entrado antes. ¿Cuánto se suele subir?',
    opts: ['2,5 ciegas', '5 ciegas', '10 ciegas'], ok: 0,
    why: 'Lo habitual online son 2,5 ciegas. En vivo se sube algo más, entre 3 y 4.',
    link: '/guias/cuanto-subir-preflop/' },
  { q: 'Dos jugadores han hecho limp. Tu subida normal es de 2,5 ciegas. ¿Cuánto subes ahora?',
    opts: ['2,5 ciegas', '4,5 ciegas', '10 ciegas'], ok: 1,
    why: 'Súmale 1 ciega por cada limp: 2,5 + 2 = 4,5 ciegas.',
    link: '/guias/cuanto-subir-preflop/' },
  { q: 'Tienes un 30% de equity y las pot odds piden un 25%. ¿Qué haces?',
    opts: ['Pagar', 'Retirarte', 'Da igual'], ok: 0,
    why: 'Si tu equity es mayor que lo que piden las pot odds, pagar gana dinero a la larga.',
    link: '/glosario/equity/' },
  { q: 'Pagas 20 para ganar un bote de 60 y ganas el 40% de las veces. ¿Cuál es el EV de pagar?',
    opts: ['−12', '0', '+12'], ok: 2,
    why: '0,40 × 60 − 0,60 × 20 = 24 − 12 = +12. Cada vez que pagas en esta situación ganas 12 de media.',
    link: '/glosario/ev/' },
  { q: 'Tú tienes 200 fichas y tu rival 80. ¿Cuál es el stack efectivo?',
    opts: ['80', '140', '200'], ok: 0,
    why: 'Es el menor de los dos: contra ese rival no puedes ganar ni perder más de 80 en esta mano.',
    link: '/glosario/stack-efectivo/' },
  { q: 'Tienes J♠10♠ y la mesa es Q♠9♥3♠. ¿Cuántos outs tienes?',
    opts: ['9', '15', '17'], ok: 1,
    why: '9 para color más 8 para escalera (K y 8), pero K♠ y 8♠ ya estaban contadas: 9 + 6 = 15.',
    link: '/glosario/outs/' },
  { q: 'All-in antes del flop: AQ contra AK. ¿Cuánto gana AQ?',
    opts: ['Un 25%', 'Un 45%', 'Un 60%'], ok: 0,
    why: 'AQ está dominada: comparten el as y la otra carta del rival es mejor. Solo gana 1 de cada 4 veces.',
    link: '/manos/aqo/' },
  { q: 'All-in antes del flop: 22 contra AK de distinto palo. ¿Quién es favorito?',
    opts: ['22, por poco', 'AK, claramente', 'Exactamente 50-50'], ok: 0,
    why: 'Una pareja, aunque sea la más baja, gana ligeramente a dos cartas altas: 22 gana alrededor del 52%.',
    link: '/manos/22/' },
  { q: 'Tienes JJ. ¿Qué probabilidad hay de que salga al menos una Q, K o A en el flop?',
    opts: ['20%', '40%', '57%'], ok: 2,
    why: 'Hay 12 cartas por encima: más de la mitad de las veces sale alguna. Por eso JJ es una mano incómoda.',
    link: '/manos/jj/' },
  { q: 'Subiste antes del flop y te pagan 3 jugadores. Flop 9♥8♥6♣ y no tienes nada. ¿Qué haces?',
    opts: ['Apostar para representar', 'Pasar', 'All-in'], ok: 1,
    why: 'Contra 3 rivales en un flop tan conectado, alguno habrá ligado algo. La c-bet de farol aquí pierde dinero.',
    link: '/glosario/c-bet/' },
  { q: 'Subes desde UTG y paga la ciega grande. ¿Qué flop favorece más a tu rango?',
    opts: ['A♠K♦7♣', '7♠6♦5♣', '5♥4♥3♠'], ok: 0,
    why: 'Desde UTG tienes muchos ases y reyes fuertes; la ciega grande, muchas manos bajas y conectadas.',
    link: '/glosario/ventaja-de-rango/' },
  { q: '¿Cuándo valen más las odds implícitas?',
    opts: ['Con stacks cortos', 'Con stacks profundos y proyecto escondido', 'Con proyecto de color evidente'], ok: 1,
    why: 'Cuantas más fichas quedan detrás y menos se ve tu proyecto, más puedes cobrar cuando ligas.',
    link: '/glosario/odds-implicitas/' },
  { q: 'Abres y te hacen 3-bet. Tienes KK. ¿Qué haces?',
    opts: ['Pagar', '4-bet', 'Retirarte por miedo a AA'], ok: 1,
    why: 'Con AA y KK, 4-bet siempre. Que el rival tenga justo AA es muy raro: menos del 0,5% de las veces.',
    link: '/guias/que-hacer-contra-un-3-bet/' },
  { q: 'Tienes 20.000 fichas y la ciega grande es de 1.000. ¿Cuántas ciegas tienes?',
    opts: ['10', '20', '200'], ok: 1,
    why: '20.000 ÷ 1.000 = 20 ciegas. Con 20 o menos, el juego antes del flop se simplifica mucho.',
    link: '/glosario/ciegas/' }
];
